version: '3.8'
services:
  rce-client:
    container_name: 'client'
    build:
      context: './client'
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    command: 'npm run dev'
  rce-server:
    container_name: 'server'
    build:
      context: './server'
      dockerfile: Dockerfile
    volumes:
      - './server:/app'
      - '/app/node_modules'
    ports:
      - '8000:8000'
    command: 'npm run dev'